### ISSUE TITLE
Kahlan example doesn't work

### ISSUE THREAD

**Issue by flip111** [crysalead/kahlan#126]
Example: https://kahlan.readthedocs.org/en/latest/getting-started/

```
PHP Fatal error:  Uncaught Error: Call to a member function write() on null in C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php:541
Stack trace:
#0 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Kahlan\Filter\Chain))
#1 C:\dev\console\text\vendor\crysalead\kahlan\src\Filter\Filter.php(213): call_user_func_array(Object(Closure), Array)
#2 C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php(551): Kahlan\Filter\Filter::on(Object(Kahlan\Cli\Kahlan), 'coverage', Array, Object(Closure))
#3 C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php(472): Kahlan\Cli\Kahlan->_coverage()
#4 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Kahlan\Filter\Chain))
#5 C:\dev\console\text\vendor\crysalead\kahlan\src\Filter\Filter.php(213): call_user_func_array(Object(Closure), Array)
#6 C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php(473): Kahlan\Filter\Filter::on(Object(Kahlan\Cli\Kahlan), 'reporters', Array, Object(Closure))
#7 C:\dev\console\text\vendor\cry in C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php on line 541

Fatal error: Uncaught Error: Call to a member function write() on null in C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php:541
Stack trace:
#0 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Kahlan\Filter\Chain))
#1 C:\dev\console\text\vendor\crysalead\kahlan\src\Filter\Filter.php(213): call_user_func_array(Object(Closure), Array)
#2 C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php(551): Kahlan\Filter\Filter::on(Object(Kahlan\Cli\Kahlan), 'coverage', Array, Object(Closure))
#3 C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php(472): Kahlan\Cli\Kahlan->_coverage()
#4 [internal function]: Kahlan\Cli\Kahlan->Kahlan\Cli\{closure}(Object(Kahlan\Filter\Chain))
#5 C:\dev\console\text\vendor\crysalead\kahlan\src\Filter\Filter.php(213): call_user_func_array(Object(Closure), Array)
#6 C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php(473): Kahlan\Filter\Filter::on(Object(Kahlan\Cli\Kahlan), 'reporters', Array, Object(Closure))
#7 C:\dev\console\text\vendor\cry in C:\dev\console\text\vendor\crysalead\kahlan\src\Cli\Kahlan.php on line 541
```

platform: Windows 7 64 bits, PHP 7.0.4

**Comment by jails** [comment]
PHPDBG SAPI has not been detected or Xdebug is not installed so the code coverage is unavailalbe.

use:
```
./bin/kahlan
```

with no parameter instead.

But thanks for the head up, I'll change this to make this error more descriptive for the next version.

**Comment by flip111** [comment]
That's strange that phpdbg is not detected, i think it ships from php version 5.6 by default (and also php 7). Talking about more descriptive error messages: kahlan also crashes when it's supplied with a path that doesn't exist. However the default php message about this is already quite descriptive. It would look better if it was handled by kahlan though.

I will close this as soon as i am on the right computer again to test it.

**Comment by jails** [comment]
phpdbg is an external interpreter. But you can use it to run kahlan's spec like so:
```
phpdbg -qrr ./bin/kahlan --coverage
```

**Comment by flip111** [comment]
`./bin/kahlan` works, not sure what the deal is with the phpdbg way of doing things

```
C:\dev\console\text>phpdbg -qrr bin\kahlan --coverage

dir=$(d=${0%[/\\]*}; cd "$d"; cd "../vendor/crysalead/kahlan/bin" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/kahlan" "$@"
```
